---
# tasks file for myrole

- name: Update apt cache
  apt:
    update_cache: yes

# https://github.com/nodesource/distributions
- name: Install 
  apt:
    name:
      - ca-certificates
      - gnupg
      - gpg
    state: latest

- name: Create directory /etc/apt/keyrings if not exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download nodesource repository GPG key
  get_url:
    url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
    dest: /tmp/nodesource-repo.gpg.key

- name: Import nodesource repository GPG key to /etc/apt/keyrings/nodesource.gpg
  shell: gpg --dearmor < /tmp/nodesource-repo.gpg.key > /etc/apt/keyrings/nodesource.gpg

- name: Create nodesource.list file
  lineinfile:
    path: /etc/apt/sources.list.d/nodesource.list
    line: "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_{{ NODE_MAJOR }}.x nodistro main"
    create: yes

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Node.js using apt
  apt:
    name: nodejs
    state: present
    update_cache: yes
    force_apt_get: yes