---
# tasks file for myrole

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install git
  apt:
    name: git
    state: present

- name: git clone
  git:
    repo: https://github.com/tldraw/tldraw-sockets-example.git
    dest: /var/tldraw-sockets-example
    force: yes

- name: sed package.json
  shell: >
    sed -i.bak 's/"dev": "concurrently \\"vite\\" \\"HOST=localhost PORT=1234 npx partykit dev\\" --kill-others"/"dev": "concurrently \\"vite --host 0.0.0.0\\" \\"HOST=0.0.0.0 PORT=1234 npx partykit dev\\" --kill-others"/' /var/tldraw-sockets-example/package.json

- name: npm install
  npm:
    path: /var/tldraw-sockets-example
    state: present

- name: npm run build
  command:
    cmd: npm run build
    chdir: /var/tldraw-sockets-example

- name: systemd service
  template:
    src: tldraw-sockets-example.service.j2
    dest: /etc/systemd/system/tldraw-sockets-example.service
  notify: restart tldraw-sockets-example